[package]
name = "bbml"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ratatui = "0.25.0"
tl = "0.7.7"
log = { workspace = true }

[dev-dependencies]
pretty_assertions = "1.4.0"