image: "docker.io/rust:1-slim-buster"

stages:
  - doc

pages:
  stage: doc
  before_script:
  - apt update && apt install pkg-config openssl-dev
  script:
  - cargo doc
  - mv target/doc www
  - mv www/doc-index.html www/doc/index.html
  - mv www public
  artifacts:
    paths:
    - public
  only:
  - main
