name: Publish to crates.io

on:
  workflow_call:
    inputs:
      plan:
        required: true
        type: string

jobs:
  publish-crates-io:
    name: publish-crates-io
    runs-on: ubuntu-20.04
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: dtolnay/rust-toolchain@stable

      - name: cargo-release Cache
        id: cargo_release_cache
        uses: actions/cache@v3
        with:
          path: ~/.cargo/bin/cargo-release
          key: ${{ runner.os }}-cargo-release

      - run: cargo install cargo-release
        if: steps.cargo_release_cache.outputs.cache-hit != 'true'

      - name: cargo login
        run: cargo login ${{ secrets.CRATES_IO_API_TOKEN }}

      - uses: actions/checkout@v3

      # allow-branch HEAD is because GitHub actions switches
      # to the tag while building, which is a detached head
      - name: "cargo release publish"
        run: |-
          cargo release \
            publish \
            --workspace \
            --allow-branch HEAD \
            --no-confirm \
            --no-verify \
            --execute
