name: Publish to crates.io

on:
  workflow_call:
    inputs:
      plan:
        required: true
        type: string

jobs:
  publish-crates-io:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
        with:
          ref: main
          fetch-depth: 0
      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable

      - name: cargo login
        run: cargo login ${{ secrets.CRATES_IO_API_TOKEN }}

      - run: cargo publish -p edlearn_client --no-verify --allow-dirty
      - run: cargo publish -p bbml --no-verify --allow-dirty
      - run: cargo publish -p edlearn_tui --no-verify --allow-dirty
